services:
  database:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_DB: solita
      POSTGRES_USER: xuefeng
      POSTGRES_PASSWORD: password
    ports:
      - 3002:5432
    container_name: database-solita-dev-xuefeng

  server:
    image: server-solita-dev-xuefeng
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - 3001:3001
    container_name: server-solita-dev-xuefeng
    depends_on:
      - database
