version: '3'

services:
  database:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_DB: solita
      POSTGRES_USER: xuefeng
      POSTGRES_PASSWORD: password
      TZ: Europe/Helsinki
      PGTZ: Europe/Helsinki
    ports:
      - 3002:5432
    volumes:
      - ./server/data:/var/lib/postgresql/data
    container_name: database-solita-dev-xuefeng

  database-test:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Europe/Helsinki
      PGTZ: Europe/Helsinki
    ports:
      - 3003:5432
    container_name: database-test-solita-dev-xuefeng

  server:
    image: server-solita-dev-xuefeng
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    environment:
      TZ: Europe/Helsinki
      DATABASE_URL: postgres://xuefeng:password@database:5432/solita
      PORT: 3001
    ports:
      - 3001:3001
    volumes:
      - ./server:/usr/src/app
    container_name: server-solita-dev-xuefeng
    depends_on:
      - database
    command: ["./wait-for-postgres.sh", "database", "npm", "run", "dev"]
  
  client:
    image: client-solita-dev-xuefeng
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    environment:
      TZ: Europe/Helsinki
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    container_name: client-solita-dev-xuefeng
    depends_on:
      - server
    command: ["./wait-for-server.sh", "npm", "start"]