version: '3'

services:
  database-test:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Europe/Helsinki
      PGTZ: Europe/Helsinki
    ports:
      - 3003:5432
    container_name: database-test

  server:
    image: server-solita-dev-xuefeng
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    environment:
      TZ: Europe/Helsinki
    ports:
      - 3001:3001
    volumes:
      - ./server:/usr/src/app
    container_name: server-solita-dev-xuefeng
    depends_on:
      - database-test
    command: ["./wait-for-test.sh", "database-test", "npm", "run", "ci"]