name: Development pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  Server:
    runs-on: ubuntu-22.04
    steps:
      - name: Check files
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set working directory
        working-directory: server/
      - name: Install npm
        run: npm ci
      - name: Eslint
        run: npm run lint
      - name: Run docker-compose
        run: |
          cd ..
          docker-compose -f docker-compose.ci.yml up -d
      - name: Tests
        run: npm run test
  Client:
    runs-on: ubuntu-22.04
    steps:
      - name: Check files
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set working directory
        working-directory: client/
      - name: Install npm
        run: npm ci
      - name: Eslint
        run: npm run lint
      - name: Tests
        run: npm run test
