name: Development pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  Server:
    runs-on: ubuntu-22.04
    steps:
      - name: Check files
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install npm
        run: |
          cd server
          npm install
      - name: Eslint
        run: |
          cd server
          npm run lint
      - name: Run docker-compose
        run: docker-compose -f docker-compose.ci.yml up -d
      - name: Tests
        run: |
          cd server
          npm run test